### ISSUE TITLE
TYPO WITH DESCRIPTION ON YCOMBINATOR SITE

### ISSUE THREAD

**Issue by Frediflexta** [Atri-Labs/framework-docs#100]
On YCombinator homepage, where you guys were describing Atri framework. I found this typo...

![Screenshot 2023-02-13 at 11 09 48 AM](https://user-images.githubusercontent.com/26186206/218432105-37ea225c-7abb-4165-95f7-9185b4722cf3.png)

The sentence underlined should be rewritten, 2021 was 2 years ago 😅, Maybe it should be corrected to something like, "We launched on 'date & month' of 2021, and in 3 months we had 24,000 downloads...".

**Comment by darshitac11** [comment]
@Frediflexta - thanks for pointing it out. Changed the founding year to 2022 - btw we launched in late Sep 2022
