### ISSUE TITLE
Improve `Use a template` page

### ISSUE THREAD

**Issue by cruxcode** [Atri-Labs/framework-docs#34]
Improve Use a templatehttps://docs.atrilabs.com/guides-frontend/template/use-template/

Add a section in the page that tells the user how to get popular templates from here https://github.com/Atri-Labs/atri-templates by following the steps described in it's README here https://github.com/Atri-Labs/atri-templates#how-to-use-a-template

**Comment by darshitac11** [comment]
We need to differentiate between using a template that was created in the current project vs. using a template from atri-templates repo.
